services:
  n8n:
    build:
      context: .
      dockerfile: dockerfile-n8n-python
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
      - ./scripts:/scripts  # (opcional) montar scripts locais
    restart: unless-stopped

volumes:
  n8n_data:
